language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.3
  - 2.3.1

services:
  - postgresql

before_install:
  - gem install bundler

before_script:
  - bundle update

script:
  - cd spec/dummy && bundle exec rake db:drop db:create db:migrate
  - cd ../.. && bundle exec rake spec
