default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: <%= ENV.fetch('DB_REAPING_FREQ') { 10 } %>
  port: 5432

development:
  <<: *default
  database: shortener_development

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'shortener_test' } %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: shortener
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
